// Pulse Width Modulation (PWM) Generator
// Generates a PWM signal with a specified duty and period cycle. `pwm_out`
// signal is high for `DUTY_CYCLES` clock cycles and low for the remainder
// in `PERIOD_CYCLES` clock cycles. Local `count` signal generated by
// Modulo N Counter
//
// Parameters:
//   PERIOD_CYCLES:   - Number of clock cycles in one PWM period
//                      (default: 50_000_000)
//   DUTY_CYCLES:     - Number of clock cycles output is high
//                      (default: 25_000_000)
//
// Ports:
//   clk:             - Clock input
//   rst:             - Asynchronous reset input
//   pwm_out:         - PWM output signal, high when within duty cycle,
//                      low when outside duty cycle
//
// Local Variables:
//   CountWidth:      - Bit width of parameter PERIOD_CYCLES.

`timescale 1ns / 1ps

module pwm_generator #(
    // Number of clock cycles in one PWM period
    parameter int PERIOD_CYCLES = 50_000_000,

    // Number of clock cycles output is high
    parameter int DUTY_CYCLES = 25_000_000
) (
    input  logic clk,
    input  logic rst,
    output logic pwm_out
);

  // Declare local parameters and signals
  // (+1'b1) is needed here to cover edge cases when PERIOD_CYCLES are powers
  // of 2, otherwise there will be integer overflow when DUTY_CYCLES is equal
  // to PERIOD_CYCLES where localparam `DutyCycles` will equal to 0
  localparam int CountWidth = $clog2(PERIOD_CYCLES) + 1'b1;
  localparam logic [CountWidth-1:0] DutyCycles = CountWidth'(DUTY_CYCLES);
  logic [CountWidth-1:0] count;

  // Instaniate Modulo N Counter with N = PERIOD_CYCLES.
  mod_n_counter #(
      .N(PERIOD_CYCLES),
      .WIDTH(CountWidth)
  ) u_period_cycle_count (
      .clk(clk),
      .rst(rst),
      .enable(1'b1),
      .count(count)
  );

  // `pwm_out` is high as for period of DutyCycles within PeriodCycles,
  // past period of DutyCycles, `pwm_out` is low for rest of PeriodCycles.
  always_comb begin
    if (count < DutyCycles) pwm_out = 1'b1;
    else pwm_out = 1'b0;
  end

endmodule
